#!/usr/bin/env bash
set -euo pipefail

NAME=mypkg
VERSION=0

# clone upstream
git clone https://github.com/rh-mcermak/cow.git ${NAME}-${VERSION}

# create tarball
tar czf ${NAME}-${VERSION}.tar.gz ${NAME}-${VERSION}

# build SRPM
rpmbuild -bs \
    --define "_sourcedir $PWD" \
    --define "_srcrpmdir $PWD" \
    ${NAME}.spec
